import {z} from 'zod';
import {BIOME_FAMILIES,type SharedTerrain,type WorldManifest} from './sharedWorld';
import {scenePartSchema,expandSceneRecipe} from './sceneGrammar';
import {sceneEnvironmentSchema} from './worldEnvironment';
const finite=z.number().finite().min(-1e9).max(1e9),point=z.object({x:finite,y:finite,z:finite}),id=z.string().min(1).max(200);
export const sharedTerrainSchema:z.ZodType<SharedTerrain>=z.object({version:z.literal(1),environments:z.array(z.object({id,x:finite,z:finite,radius:z.number().positive().max(30000),overlays:sceneEnvironmentSchema.shape.overlays})).max(128).optional(),climate:z.array(z.object({id,biome:z.enum(BIOME_FAMILIES),x:finite,z:finite,radius:z.number().min(128).max(100000),temperature:z.number().min(-80).max(80),precipitation:z.number().min(0).max(20000)})).max(128),edits:z.array(z.object({id,kind:z.enum(['road','foundation']),points:z.array(point).min(1).max(20000),width:z.number().positive().max(500),feather:z.number().nonnegative().max(500),footprint:z.array(z.object({x:finite,z:finite})).min(3).max(64).optional()})).max(50000)});
/** Imported authoritative geometry is validated before any spatial-index loops. */
export function assertWorldManifest(value:unknown):asserts value is WorldManifest{
  const m=z.object({version:z.literal(1),id,seed:z.number().int().min(0).max(2147483647),revision:z.number().int().positive(),generatorVersion:z.literal(1),climateVersion:z.literal(1),hydrologyVersion:z.literal(1),startingRadius:z.number().positive().max(1000000),origin:z.object({x:finite,z:finite}),terrain:sharedTerrainSchema,requests:z.array(z.object({id,name:id,description:z.string().max(4000),roles:z.record(z.string(),z.number().int().min(0).max(96)),connectsTo:z.array(id).max(64),modes:z.array(z.enum(['road','ferry'])).max(2)})).max(128),locations:z.array(z.object({id,requestId:id,position:point,radius:z.number().positive().max(10000),settlement:z.object({buildings:z.array(z.object({id,position:point,entrance:point,width:z.number().positive().max(100),depth:z.number().positive().max(100),height:z.number().positive().max(100),recipe:z.array(z.unknown()).max(48)})).max(256),streets:z.array(z.unknown()).max(2048),docks:z.array(z.unknown()).max(32)})})).max(128),transport:z.array(z.object({id,from:id,to:id,mode:z.enum(['road','ferry']),points:z.array(point).min(2).max(20000),speed:z.number().positive().max(20),width:z.number().positive().max(100)})).max(1024),styles:z.array(z.unknown()).min(1).max(256),waterBodies:z.array(z.unknown()).max(2048),checkpoints:z.array(z.unknown()).max(2048)}).safeParse(value);
  if(!m.success)throw new Error(`Unsupported or invalid shared world: ${m.error.issues.slice(0,3).map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')}`);
  const positive=z.number().finite().positive(),nonnegative=z.number().finite().nonnegative();
  const bridge=z.object({id,start:point,end:point,family:z.enum(['timber','stone','suspension']),width:positive.max(100),clearance:nonnegative});
  const route=z.object({id,from:id,to:id,mode:z.enum(['road','ferry']),points:z.array(point).min(2).max(20000),width:positive.max(100),bridges:z.array(bridge).max(2048),length:positive,maxGrade:nonnegative.max(1),speed:positive.max(20),waterBodyId:id.optional()});
  const recipe=z.array(scenePartSchema).min(1).max(48).refine(parts=>expandSceneRecipe(parts).length<=384,'Recipe exceeds expanded geometry budget');
  const details=z.object({requests:z.array(z.object({id,environment:sceneEnvironmentSchema.optional(),purpose:z.string().max(4000),biome:z.enum(BIOME_FAMILIES).optional(),intent:z.object({landform:z.enum(['any','lowland','highland','valley','ridge']),water:z.enum(['none','coast','river']),forest:nonnegative.max(1)}),island:z.boolean(),scale:z.enum(['wilderness','village','town','city']),styleId:id,status:z.enum(['pending','located','ready','failed']),roles:z.record(id,z.number().int().nonnegative().max(96)).refine(r=>Object.values(r).reduce((a,b)=>a+b,0)<=256),recipes:z.record(id,recipe).optional()})),locations:z.array(z.object({name:id,biome:z.enum(BIOME_FAMILIES),slope:nonnegative,relief:nonnegative,settlement:z.object({id,buildings:z.array(z.object({id,role:id,yaw:finite,recipe,footprint:z.array(z.object({x:finite,z:finite})).min(3).max(64).optional(),program:z.object({family:id,floors:z.number().int().min(1).max(3),rooms:z.array(id).max(32),style:id}).optional()})),streets:z.array(route),docks:z.array(z.object({id,land:point,water:point,width:positive.max(100),waterBodyId:id}))})})),transport:z.array(route),styles:z.array(z.object({id,name:id,family:z.enum(['timber','courtyard','earthen','fortress']).optional(),roofPitch:z.number().min(.2).max(6).optional(),floorHeight:z.number().min(2.7).max(4).optional(),material:z.enum(['timber','masonry']),roofColor:z.string().regex(/^#[\da-f]{6}$/i),wallColor:z.string().regex(/^#[\da-f]{6}$/i),roofCurve:finite.min(-1).max(1),bays:z.number().int().min(1).max(6),age:nonnegative.max(1)})),waterBodies:z.array(z.object({id,level:finite,cells:z.array(z.string().regex(/^-?\d+\/-?\d+$/)).max(1000000),cellSize:positive.min(1).max(8192),kind:z.enum(['lake','ocean','river']),outlet:z.object({x:finite,z:finite}).optional()})),checkpoints:z.array(z.object({stage:id,revision:z.number().int().positive(),completed:z.array(id).max(128)})),removedEntityIds:z.array(id).max(50000).optional()}).safeParse(value);
  if(!details.success)throw new Error(`Invalid shared world plan: ${details.error.issues.slice(0,3).map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')}`);
  const polygon=z.array(z.object({x:finite,z:finite})).min(3).max(64);
  const extension=z.object({version:z.literal(2).optional(),nodes:z.array(point.extend({id})).max(10000).optional(),parcels:z.array(z.object({id,polygon,frontage:point,districtId:id,buildingId:id})).max(256).optional(),publicSpaces:z.array(z.object({id,position:point,polygon,kind:z.enum(['market','waterfront','court'])})).max(64).optional(),structures:z.array(z.object({id,position:point,yaw:finite,recipe})).max(4096).optional()});
  for(const location of (value as WorldManifest).locations){
    const parsed=extension.safeParse(location.settlement);
    if(!parsed.success)throw new Error('Invalid settlement revision: '+parsed.error.issues[0].message);
  }
  const ids=new Set(m.data.locations.map(l=>l.id));if(ids.size!==m.data.locations.length||m.data.transport.some(r=>!ids.has(r.from)||!ids.has(r.to)))throw new Error('Shared world contains duplicate locations or dangling routes');
}
