import { z } from 'zod';
import { prepareLanguageSettings } from './managedLanguage';
import { completeLocalChat, extractJson } from './openAiClient';
import {sceneEnvironmentSchema,inferSceneEnvironment} from '../domain/worldEnvironment';
import { siteIntentSchema } from '../domain/worldSite';
import {scenePartSchema,expandSceneRecipe} from '../domain/sceneGrammar';
import { BIOME_FAMILIES, type SceneRequest, type RegionalStyle } from '../domain/sharedWorld';
import type { CampaignSettings } from '../domain/types';
const output=z.object({scenes:z.array(z.object({id:z.string().min(1).max(120),name:z.string().min(1).max(120).optional(),description:z.string().max(4000).optional(),purpose:z.string(),environment:sceneEnvironmentSchema.optional(),recipes:z.record(z.string(),z.array(scenePartSchema).min(1).max(48)).optional(),biome:z.enum(BIOME_FAMILIES).optional(),intent:siteIntentSchema,island:z.boolean(),scale:z.enum(['wilderness','village','town','city']),roles:z.record(z.string().max(40),z.number().int().min(0).max(96)).refine(r=>Object.values(r).reduce((a,b)=>a+b,0)<=256,'Settlement program exceeds 256 buildings'),connectsTo:z.array(z.string()).max(24),modes:z.array(z.enum(['road','ferry'])).min(1),style:z.object({family:z.enum(['timber','courtyard','earthen','fortress']).optional(),roofPitch:z.number().min(.2).max(6).optional(),floorHeight:z.number().min(2.7).max(4).optional(),name:z.string().max(80),material:z.enum(['timber','masonry']),roofColor:z.string().regex(/^#[\da-f]{6}$/i),wallColor:z.string().regex(/^#[\da-f]{6}$/i),roofCurve:z.number().min(-1).max(1),bays:z.number().int().min(1).max(6),age:z.number().min(0).max(1)}).optional()})).min(1).max(64)});
export async function directWorldRequests(requests:SceneRequest[],settings:CampaignSettings,signal?:AbortSignal,onProgress?:(stage:string,message:string,detail?:string)=>void):Promise<{requests:SceneRequest[];styles:RegionalStyle[];warning?:string}>{
  onProgress?.('Local model','Preparing the local language model');
  const configured=await prepareLanguageSettings(settings,signal,p=>onProgress?.('Local model',p.message,p.totalBytes>0?`${Math.round(p.completedBytes/p.totalBytes*100)}% of model setup`:undefined));if(!configured.localAiEndpoint||!configured.useLocalAiForMaps)return {requests,styles:[]};
  const messages:Array<{role:'system'|'user'|'assistant';content:string}>=[{role:'system',content:'Plan physical scene requirements for one persistent fantasy world. Return only the provided JSON schema. Keep every input scene ID exactly once. When the prompt requests additional distinct gameplay locations, add up to 12 scenes with unique IDs, names and descriptions and connect them to the original scene network. Describe requirements and relationships, never coordinates. Preserve explicit geography, required building roles and transport choices. A harbor town needs many homes, warehouses, workshops, public buildings and dock access; a landmark or wilderness can have no buildings. Culture is independent of climate. Specify distinct building roles, district purposes and construction traditions in each scene description. The engine builds varied parcel-fitted architecture; omit recipes unless a specific custom structure is required. Castles need a keep, hall, service ranges and accommodation; the engine reserves courts and adds terrain-adapted defenses. Optionally provide structural recipes by building role, using frame/roof/repeated structural operators, with accessible floors and doors. The engine reserves parcels large enough for recipes without shrinking their doors. Use biome only when a particular climate family was explicitly requested. Unsupported impossible requirements must not be silently removed.'},{role:'user',content:JSON.stringify({scenes:requests,schema:z.toJSONSchema(output)})}];
  let failure='',attempts=0;const deadline=Date.now()+180000;let lastProgress=0;
  for(let attempt=0;attempt<3;attempt++)try{
    attempts++;onProgress?.('Scene planning',attempt?'Repairing scene requirements':'Reading scene requirements','Local planning may take several minutes; output progress appears as the model responds.');
    const content=await completeLocalChat({endpoint:configured.localAiEndpoint,model:configured.localAiModel,responseSchema:z.toJSONSchema(output),messages,temperature:.35,maxTokens:6500,signal,timeoutMs:Math.max(1,deadline-Date.now()),onProgress:characters=>{if(Date.now()-lastProgress<500)return;lastProgress=Date.now();onProgress?.('Scene planning','The local model is planning your scenes',`${characters.toLocaleString()} response characters received${attempt?` ? repair ${attempt} of 2`:''}`);}});const result=output.parse(extractJson(content));
    if(result.scenes.length>requests.length+12||new Set(result.scenes.map(s=>s.id)).size!==result.scenes.length||requests.some(r=>!result.scenes.some(s=>s.id===r.id))||result.scenes.some(s=>s.connectsTo.some(id=>id===s.id||!result.scenes.some(r=>r.id===id))))throw new Error('Scene IDs or destination relationships do not match the requested scene list');
    for(const scene of result.scenes)for(const parts of Object.values(scene.recipes??{}))if(!parts.some(p=>(p.shape==='frame'||p.shape==='house'))||!parts.some(p=>p.shape==='roof')||expandSceneRecipe(parts).length>384)throw new Error('Building recipes need an accessible frame and roof within the geometry budget');
    const styles:RegionalStyle[]=result.scenes.filter(s=>s.style).map(s=>({id:`style-${s.id}`,...s.style!}));
    const expanded:SceneRequest[]=[...requests,...result.scenes.filter(s=>!requests.some(r=>r.id===s.id)).map(s=>({id:s.id,name:s.name??s.purpose,description:s.description??s.purpose,purpose:s.purpose,intent:s.intent,island:s.island,scale:s.scale,roles:s.roles,connectsTo:s.connectsTo,modes:s.modes,styleId:s.style?'style-'+s.id:'regional-timber',status:'pending' as const}))];
    return {styles,requests:expanded.map(r=>{const s=result.scenes.find(s=>s.id===r.id)!;return {...r,...s,environment:r.environment?.stratum==='underground'?r.environment:s.environment??r.environment??inferSceneEnvironment(s.description??s.purpose),biome:r.biome??s.biome,intent:{...s.intent,water:r.intent.water!=='none'?r.intent.water:s.intent.water,landform:r.intent.landform!=='any'?r.intent.landform:s.intent.landform},roles:Object.fromEntries([...new Set([...Object.keys(r.roles),...Object.keys(s.roles)])].map(role=>[role,Math.max(r.roles[role]??0,s.roles[role]??0)])),island:r.island||s.island,styleId:s.style?`style-${r.id}`:r.styleId};})};
  }catch(error){signal?.throwIfAborted();failure=error instanceof Error?error.message:String(error);if(Date.now()>=deadline)break;messages.push({role:'user',content:`Repair the requirements. Validation failed: ${failure.slice(0,1200)}. Return the complete corrected JSON.`});}
  return {requests,styles:[],warning:`Local planning could not be validated ${attempts===3?'after two repairs':'within the three-minute planning budget'}. The requested scene requirements are preserved. You can continue with the saved requirements or edit them in Connected world.`};
}



